// @ts-check

import BaseRelationship from "./base.js"
import * as inflection from "inflection"

export default class VelociousDatabaseRecordHasOneRelationship extends BaseRelationship {
  /** @returns {string} - Result.  */
  getForeignKey() {
    if (!this.foreignKey) {
      this.foreignKey = `${inflection.underscore(this.modelClass.name)}_id`
    }

    return this.foreignKey
  }

  /** @returns {string | undefined} - Result.  */
  getInverseOf() {
    if (!this._inverseOf && !this._autoGenerateInverseOfAttempted) {
      this._autoGenerateInverseOfAttempted = true

      // Only make auto-inverse-of if the relationships name matches the target model class's name
      const targetClassSimpleName = `${this.getRelationshipName().substring(0, 1).toUpperCase()}${this.getRelationshipName().substring(1, this.getRelationshipName().length)}`

      const targetModelClass = this.getTargetModelClass()

      if (targetModelClass && targetClassSimpleName == targetModelClass.name) {
        // Only make auto-inverse-of if the expected relationship exist in a has-one or has-many form
        const targetClassRelationshipNames = targetModelClass.getRelationshipNames()
        const autoGeneratedBelongsToInverseOfName = `${this.modelClass.name.substring(0, 1).toLowerCase()}${this.modelClass.name.substring(1, this.modelClass.name.length)}`

        if (targetClassRelationshipNames.includes(autoGeneratedBelongsToInverseOfName)) {
          this._inverseOf = autoGeneratedBelongsToInverseOfName
        }
      }
    }

    return this._inverseOf
  }
}
