before_script:
  - cp spec/dummy/config/databases.peakflow.mjs spec/dummy/config/databases.js
  - npm install
  - wait-for-it mariadb:3306
services:
  mariadb:
    environment:
      MYSQL_USER: peakflow
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: velocious_test
    image: mariadb:latest
    expose:
      - 3306
    mem_limit: 4096m
    restart_policy: on-failure
script:
  - npm test
