before_install:
  - curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  - sudo apt-get install -y nodejs
before_script:
  - cp spec/dummy/src/config/database.peakflow.mjs spec/dummy/src/config/database.mjs
  - npm install
  - wait-for-it mariadb:3306
services:
  mariadb:
    environment:
      MYSQL_USER: peakflow
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: velocious_test
    image: mariadb:latest
    expose:
      - 3306
    mem_limit: 4096m
    restart_policy: on-failure
script:
  - npm test
