before_install:
  - sudo mkdir -p /etc/apt/keyrings
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --no-tty --batch --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
  - sudo apt-get update
  - sudo apt-get install -y nodejs
before_script:
  - npm install
services:
  mariadb:
    environment:
      MYSQL_USER: peakflow
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: velocious_test
    image: mariadb:latest
    expose:
      - 3306
    mem_limit: 4096m
    restart_policy: on-failure
  mssql:
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Super-Secret-Password
    image: mcr.microsoft.com/mssql/server:2022-latest
    expose:
      - 1433
    mem_limit: 4096m
    restart_policy: on-failure
builds:
  build_1:
    name: MariaDB
    script:
      - cp spec/dummy/src/config/configuration.peakflow.mariadb.js spec/dummy/src/config/configuration.js
      - wait-for-it mariadb:3306
      - npm test
  build_1:
    name: MS-SQL
    script:
      - cp spec/dummy/src/config/configuration.peakflow.mssql.js spec/dummy/src/config/configuration.js
      - wait-for-it mssql:1433
      - npm test
  build_2:
    name: SQLite
    script:
      - cp spec/dummy/src/config/configuration.peakflow.sqlite.js spec/dummy/src/config/configuration.js
      - npm test
