before_install:
  - sudo mkdir -p /etc/apt/keyrings
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
  - sudo apt-get update
  - sudo apt-get install -y nodejs
before_script:
  - cp spec/dummy/src/config/configuration.peakflow.mjs spec/dummy/src/config/configuration.mjs
  - npm install
  - wait-for-it mariadb:3306
services:
  mariadb:
    environment:
      MYSQL_USER: peakflow
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: velocious_test
    image: mariadb:latest
    expose:
      - 3306
    mem_limit: 4096m
    restart_policy: on-failure
script:
  - npm test
