// This file is auto-generated by Velocious. Do not edit it manually — any changes
// will be overwritten the next time it is generated. Run `velocious generate:base-models` to regenerate.
import DatabaseRecord from "../../../../src/database/record/index.js"

/**
 * Attributes accepted when creating or updating SyncEntry records.
 * @typedef {object} SyncEntryWriteAttributes
 * @property {string} [id] - Value for the id attribute.
 * @property {string | null} [authenticationTokenId] - Value for the authenticationTokenId attribute.
 * @property {string} [resourceId] - Value for the resourceId attribute.
 * @property {string} [resourceType] - Value for the resourceType attribute.
 * @property {string} [syncType] - Value for the syncType attribute.
 * @property {Date | string | null} [clientUpdatedAt] - Value for the clientUpdatedAt attribute.
 * @property {string | null} [data] - Value for the data attribute.
 * @property {number | null} [serverSequence] - Value for the serverSequence attribute.
 * @property {Date | string | null} [createdAt] - Value for the createdAt attribute.
 * @property {Date | string | null} [updatedAt] - Value for the updatedAt attribute.
 */

/** @augments {DatabaseRecord<SyncEntryWriteAttributes>} */
export default class SyncEntryBase extends DatabaseRecord {
  /**
   * @returns {typeof import("../models/sync-entry.js").default}
   */
  // @ts-ignore - override narrows return type for better IntelliSense in generated model bases
  getModelClass() { return /** @type {typeof import("../models/sync-entry.js").default} */ (this.constructor) }

  /**
   * @returns {string}
   */
  id() { return this.readAttribute("id") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setId(newValue) { return this._setColumnAttribute("id", newValue) }

  /**
   * @returns {boolean}
   */
  hasId() { return this._hasAttribute(this.id()) }

  /**
   * @returns {string | null}
   */
  authenticationTokenId() { return this.readAttribute("authenticationTokenId") }

  /**
   * @param {string | null} newValue
   * @returns {void}
   */
  setAuthenticationTokenId(newValue) { return this._setColumnAttribute("authenticationTokenId", newValue) }

  /**
   * @returns {boolean}
   */
  hasAuthenticationTokenId() { return this._hasAttribute(this.authenticationTokenId()) }

  /**
   * @returns {string}
   */
  resourceId() { return this.readAttribute("resourceId") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setResourceId(newValue) { return this._setColumnAttribute("resourceId", newValue) }

  /**
   * @returns {boolean}
   */
  hasResourceId() { return this._hasAttribute(this.resourceId()) }

  /**
   * @returns {string}
   */
  resourceType() { return this.readAttribute("resourceType") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setResourceType(newValue) { return this._setColumnAttribute("resourceType", newValue) }

  /**
   * @returns {boolean}
   */
  hasResourceType() { return this._hasAttribute(this.resourceType()) }

  /**
   * @returns {string}
   */
  syncType() { return this.readAttribute("syncType") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setSyncType(newValue) { return this._setColumnAttribute("syncType", newValue) }

  /**
   * @returns {boolean}
   */
  hasSyncType() { return this._hasAttribute(this.syncType()) }

  /**
   * @returns {Date | null}
   */
  clientUpdatedAt() { return this.readAttribute("clientUpdatedAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setClientUpdatedAt(newValue) { return this._setColumnAttribute("clientUpdatedAt", newValue) }

  /**
   * @returns {boolean}
   */
  hasClientUpdatedAt() { return this._hasAttribute(this.clientUpdatedAt()) }

  /**
   * @returns {string | null}
   */
  data() { return this.readAttribute("data") }

  /**
   * @param {string | null} newValue
   * @returns {void}
   */
  setData(newValue) { return this._setColumnAttribute("data", newValue) }

  /**
   * @returns {boolean}
   */
  hasData() { return this._hasAttribute(this.data()) }

  /**
   * @returns {number | null}
   */
  serverSequence() { return this.readAttribute("serverSequence") }

  /**
   * @param {number | null} newValue
   * @returns {void}
   */
  setServerSequence(newValue) { return this._setColumnAttribute("serverSequence", newValue) }

  /**
   * @returns {boolean}
   */
  hasServerSequence() { return this._hasAttribute(this.serverSequence()) }

  /**
   * @returns {Date | null}
   */
  createdAt() { return this.readAttribute("createdAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setCreatedAt(newValue) { return this._setColumnAttribute("createdAt", newValue) }

  /**
   * @returns {boolean}
   */
  hasCreatedAt() { return this._hasAttribute(this.createdAt()) }

  /**
   * @returns {Date | null}
   */
  updatedAt() { return this.readAttribute("updatedAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setUpdatedAt(newValue) { return this._setColumnAttribute("updatedAt", newValue) }

  /**
   * @returns {boolean}
   */
  hasUpdatedAt() { return this._hasAttribute(this.updatedAt()) }
}
