// This file is auto-generated by Velocious. Do not edit it manually — any changes
// will be overwritten the next time it is generated. Run `velocious generate:base-models` to regenerate.
import DatabaseRecord from "../../../../src/database/record/index.js"

/**
 * Attributes accepted when creating or updating Task records.
 * @typedef {object} TaskWriteAttributes
 * @property {number} [id] - Value for the id attribute.
 * @property {number} [projectId] - Value for the projectId attribute.
 * @property {string | null} [name] - Value for the name attribute.
 * @property {string | null} [description] - Value for the description attribute.
 * @property {Date | string | null} [createdAt] - Value for the createdAt attribute.
 * @property {Date | string | null} [updatedAt] - Value for the updatedAt attribute.
 * @property {boolean | null} [isDone] - Value for the isDone attribute.
 * @property {import("../models/project.js").default} [project] - Related project record.
 * @property {import("../models/project.js").default} [reviewProject] - Related reviewProject record.
 * @property {Array<import("./comment.js").CommentWriteAttributes & {_destroy?: boolean}>} [commentsAttributes] - Nested comments attributes.
 * @property {import("./project.js").ProjectWriteAttributes} [projectAttributes] - Nested project attributes.
 */

/** @augments {DatabaseRecord<TaskWriteAttributes>} */
export default class TaskBase extends DatabaseRecord {
  /** @returns {typeof import("../models/task.js").default} */
  // @ts-ignore - override narrows return type for better IntelliSense in generated model bases
  getModelClass() { return /** @type {typeof import("../models/task.js").default} */ (this.constructor) }

  /** @returns {number} */
  id() { return this.readAttribute("id") }

  /**
   * @param {number} newValue
   * @returns {void}
   */
  setId(newValue) { return this._setColumnAttribute("id", newValue) }

  /** @returns {boolean} */
  hasId() { return this._hasAttribute(this.id()) }

  /** @returns {number} */
  projectId() { return this.readAttribute("projectId") }

  /**
   * @param {number} newValue
   * @returns {void}
   */
  setProjectId(newValue) { return this._setColumnAttribute("projectId", newValue) }

  /** @returns {boolean} */
  hasProjectId() { return this._hasAttribute(this.projectId()) }

  /** @returns {string | null} */
  name() { return this.readAttribute("name") }

  /**
   * @param {string | null} newValue
   * @returns {void}
   */
  setName(newValue) { return this._setColumnAttribute("name", newValue) }

  /** @returns {boolean} */
  hasName() { return this._hasAttribute(this.name()) }

  /** @returns {string | null} */
  description() { return this.readAttribute("description") }

  /**
   * @param {string | null} newValue
   * @returns {void}
   */
  setDescription(newValue) { return this._setColumnAttribute("description", newValue) }

  /** @returns {boolean} */
  hasDescription() { return this._hasAttribute(this.description()) }

  /** @returns {Date | null} */
  createdAt() { return this.readAttribute("createdAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setCreatedAt(newValue) { return this._setColumnAttribute("createdAt", newValue) }

  /** @returns {boolean} */
  hasCreatedAt() { return this._hasAttribute(this.createdAt()) }

  /** @returns {Date | null} */
  updatedAt() { return this.readAttribute("updatedAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setUpdatedAt(newValue) { return this._setColumnAttribute("updatedAt", newValue) }

  /** @returns {boolean} */
  hasUpdatedAt() { return this._hasAttribute(this.updatedAt()) }

  /** @returns {boolean | null} */
  isDone() { return this.readAttribute("isDone") }

  /**
   * @param {boolean | null} newValue
   * @returns {void}
   */
  setIsDone(newValue) { return this._setColumnAttribute("isDone", newValue) }

  /** @returns {boolean} */
  hasIsDone() { return this._hasAttribute(this.isDone()) }

  /**
   * @returns {import("../models/project.js").default}
   */
  project() { return /** @type {import("../models/project.js").default} */ (this.getRelationshipByName("project").loaded()) }

  /**
   * @abstract
   * @param {ConstructorParameters<typeof import("../models/project.js").default>[0]} [attributes]
   * @returns {import("../models/project.js").default}
   */
  buildProject(attributes) { void attributes; throw new Error("Not implemented") }

  /**
   * @abstract
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  loadProject() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  projectOrLoad() { return /** @type {Promise<import("../models/project.js").default | undefined>} */ (this.relationshipOrLoad("project")) }

  /**
   * @abstract
   * @param {import("../models/project.js").default} newModel
   * @returns {void}
   */
  setProject(newModel) { void newModel; throw new Error("Not implemented") }

  /**
   * @returns {import("../models/project.js").default}
   */
  reviewProject() { return /** @type {import("../models/project.js").default} */ (this.getRelationshipByName("reviewProject").loaded()) }

  /**
   * @abstract
   * @param {ConstructorParameters<typeof import("../models/project.js").default>[0]} [attributes]
   * @returns {import("../models/project.js").default}
   */
  buildReviewProject(attributes) { void attributes; throw new Error("Not implemented") }

  /**
   * @abstract
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  loadReviewProject() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  reviewProjectOrLoad() { return /** @type {Promise<import("../models/project.js").default | undefined>} */ (this.relationshipOrLoad("reviewProject")) }

  /**
   * @abstract
   * @param {import("../models/project.js").default} newModel
   * @returns {void}
   */
  setReviewProject(newModel) { void newModel; throw new Error("Not implemented") }

  /**
   * @returns {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/task.js").default, typeof import("../models/interaction.js").default>}
   */
  interactions() { return /** @type {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/task.js").default, typeof import("../models/interaction.js").default>} */ (this.getRelationshipByName("interactions")) }

  /**
   * @returns {Array<import("../models/interaction.js").default>}
   */
  interactionsLoaded() { return /** @type {Array<import("../models/interaction.js").default>} */ (this.getRelationshipByName("interactions").loaded()) }

  /**
   * @abstract
   * @returns {Promise<Array<import("../models/interaction.js").default>>}
   */
  loadInteractions() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<Array<import("../models/interaction.js").default>>}
   */
  interactionsOrLoad() { return /** @type {Promise<Array<import("../models/interaction.js").default>>} */ (this.relationshipOrLoad("interactions")) }

  /**
   * @abstract
   * @param {Array<import("../models/interaction.js").default>} newModels
   * @returns {void}
   */
  setInteractions(newModels) { void newModels; throw new Error("Not implemented") }

  /**
   * @returns {import("../models/interaction.js").default}
   */
  primaryInteraction() { return /** @type {import("../models/interaction.js").default} */ (this.getRelationshipByName("primaryInteraction").loaded()) }

  /**
   * @abstract
   * @param {ConstructorParameters<typeof import("../models/interaction.js").default>[0]} [attributes]
   * @returns {import("../models/interaction.js").default}
   */
  buildPrimaryInteraction(attributes) { void attributes; throw new Error("Not implemented") }

  /**
   * @abstract
   * @returns {Promise<import("../models/interaction.js").default | undefined>}
   */
  loadPrimaryInteraction() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<import("../models/interaction.js").default | undefined>}
   */
  primaryInteractionOrLoad() { return /** @type {Promise<import("../models/interaction.js").default | undefined>} */ (this.relationshipOrLoad("primaryInteraction")) }

  /**
   * @abstract
   * @param {import("../models/interaction.js").default} newModel
   * @returns {void}
   */
  setPrimaryInteraction(newModel) { void newModel; throw new Error("Not implemented") }

  /**
   * @returns {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/task.js").default, typeof import("../models/comment.js").default>}
   */
  comments() { return /** @type {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/task.js").default, typeof import("../models/comment.js").default>} */ (this.getRelationshipByName("comments")) }

  /**
   * @returns {Array<import("../models/comment.js").default>}
   */
  commentsLoaded() { return /** @type {Array<import("../models/comment.js").default>} */ (this.getRelationshipByName("comments").loaded()) }

  /**
   * @abstract
   * @returns {Promise<Array<import("../models/comment.js").default>>}
   */
  loadComments() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<Array<import("../models/comment.js").default>>}
   */
  commentsOrLoad() { return /** @type {Promise<Array<import("../models/comment.js").default>>} */ (this.relationshipOrLoad("comments")) }

  /**
   * @abstract
   * @param {Array<import("../models/comment.js").default>} newModels
   * @returns {void}
   */
  setComments(newModels) { void newModels; throw new Error("Not implemented") }
}
