// This file is auto-generated by Velocious. Do not edit it manually — any changes
// will be overwritten the next time it is generated. Run `velocious generate:base-models` to regenerate.
import DatabaseRecord from "../../../../src/database/record/index.js"

/**
 * Attributes accepted when creating or updating TaskBoard records.
 * @typedef {object} TaskBoardWriteAttributes
 * @property {number} [id] - Value for the id attribute.
 * @property {number} [projectId] - Value for the projectId attribute.
 * @property {string} [name] - Value for the name attribute.
 * @property {Date | string | null} [createdAt] - Value for the createdAt attribute.
 * @property {Date | string | null} [updatedAt] - Value for the updatedAt attribute.
 * @property {import("../models/project.js").default} [project] - Related project record.
 */

/** @augments {DatabaseRecord<TaskBoardWriteAttributes>} */
export default class TaskBoardBase extends DatabaseRecord {
  /** @returns {typeof import("../models/task-board.js").default} */
  // @ts-ignore - override narrows return type for better IntelliSense in generated model bases
  getModelClass() { return /** @type {typeof import("../models/task-board.js").default} */ (this.constructor) }

  /** @returns {number} */
  id() { return this.readAttribute("id") }

  /**
   * @param {number} newValue
   * @returns {void}
   */
  setId(newValue) { return this._setColumnAttribute("id", newValue) }

  /** @returns {boolean} */
  hasId() { return this._hasAttribute(this.id()) }

  /** @returns {number} */
  projectId() { return this.readAttribute("projectId") }

  /**
   * @param {number} newValue
   * @returns {void}
   */
  setProjectId(newValue) { return this._setColumnAttribute("projectId", newValue) }

  /** @returns {boolean} */
  hasProjectId() { return this._hasAttribute(this.projectId()) }

  /** @returns {string} */
  name() { return this.readAttribute("name") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setName(newValue) { return this._setColumnAttribute("name", newValue) }

  /** @returns {boolean} */
  hasName() { return this._hasAttribute(this.name()) }

  /** @returns {Date | null} */
  createdAt() { return this.readAttribute("createdAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setCreatedAt(newValue) { return this._setColumnAttribute("createdAt", newValue) }

  /** @returns {boolean} */
  hasCreatedAt() { return this._hasAttribute(this.createdAt()) }

  /** @returns {Date | null} */
  updatedAt() { return this.readAttribute("updatedAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setUpdatedAt(newValue) { return this._setColumnAttribute("updatedAt", newValue) }

  /** @returns {boolean} */
  hasUpdatedAt() { return this._hasAttribute(this.updatedAt()) }

  /**
   * @returns {import("../models/project.js").default}
   */
  project() { return /** @type {import("../models/project.js").default} */ (this.getRelationshipByName("project").loaded()) }

  /**
   * @abstract
   * @param {ConstructorParameters<typeof import("../models/project.js").default>[0]} [attributes]
   * @returns {import("../models/project.js").default}
   */
  buildProject(attributes) { void attributes; throw new Error("Not implemented") }

  /**
   * @abstract
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  loadProject() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  projectOrLoad() { return /** @type {Promise<import("../models/project.js").default | undefined>} */ (this.relationshipOrLoad("project")) }

  /**
   * @abstract
   * @param {import("../models/project.js").default} newModel
   * @returns {void}
   */
  setProject(newModel) { void newModel; throw new Error("Not implemented") }

  /**
   * @returns {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/task-board.js").default, typeof import("../models/task-board-card.js").default>}
   */
  taskBoardCards() { return /** @type {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/task-board.js").default, typeof import("../models/task-board-card.js").default>} */ (this.getRelationshipByName("taskBoardCards")) }

  /**
   * @returns {Array<import("../models/task-board-card.js").default>}
   */
  taskBoardCardsLoaded() { return /** @type {Array<import("../models/task-board-card.js").default>} */ (this.getRelationshipByName("taskBoardCards").loaded()) }

  /**
   * @abstract
   * @returns {Promise<Array<import("../models/task-board-card.js").default>>}
   */
  loadTaskBoardCards() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<Array<import("../models/task-board-card.js").default>>}
   */
  taskBoardCardsOrLoad() { return /** @type {Promise<Array<import("../models/task-board-card.js").default>>} */ (this.relationshipOrLoad("taskBoardCards")) }

  /**
   * @abstract
   * @param {Array<import("../models/task-board-card.js").default>} newModels
   * @returns {void}
   */
  setTaskBoardCards(newModels) { void newModels; throw new Error("Not implemented") }
}
