// This file is auto-generated by Velocious. Do not edit it manually — any changes
// will be overwritten the next time it is generated. Run `velocious generate:base-models` to regenerate.
import DatabaseRecord from "../../../../src/database/record/index.js"

/**
 * Attributes accepted when creating or updating User records.
 * @typedef {object} UserWriteAttributes
 * @property {number} [id] - Value for the id attribute.
 * @property {string} [email] - Value for the email attribute.
 * @property {string} [encryptedPassword] - Value for the encryptedPassword attribute.
 * @property {string | null} [reference] - Value for the reference attribute.
 * @property {Date | string | null} [createdAt] - Value for the createdAt attribute.
 * @property {Date | string | null} [updatedAt] - Value for the updatedAt attribute.
 */

/** @augments {DatabaseRecord<UserWriteAttributes>} */
export default class UserBase extends DatabaseRecord {
  /**
   * @returns {typeof import("../models/user.js").default}
   */
  // @ts-ignore - override narrows return type for better IntelliSense in generated model bases
  getModelClass() { return /** @type {typeof import("../models/user.js").default} */ (this.constructor) }

  /**
   * @returns {number}
   */
  id() { return this.readAttribute("id") }

  /**
   * @param {number} newValue
   * @returns {void}
   */
  setId(newValue) { return this._setColumnAttribute("id", newValue) }

  /**
   * @returns {boolean}
   */
  hasId() { return this._hasAttribute(this.id()) }

  /**
   * @returns {string}
   */
  email() { return this.readAttribute("email") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setEmail(newValue) { return this._setColumnAttribute("email", newValue) }

  /**
   * @returns {boolean}
   */
  hasEmail() { return this._hasAttribute(this.email()) }

  /**
   * @returns {string}
   */
  encryptedPassword() { return this.readAttribute("encryptedPassword") }

  /**
   * @param {string} newValue
   * @returns {void}
   */
  setEncryptedPassword(newValue) { return this._setColumnAttribute("encryptedPassword", newValue) }

  /**
   * @returns {boolean}
   */
  hasEncryptedPassword() { return this._hasAttribute(this.encryptedPassword()) }

  /**
   * @returns {string | null}
   */
  reference() { return this.readAttribute("reference") }

  /**
   * @param {string | null} newValue
   * @returns {void}
   */
  setReference(newValue) { return this._setColumnAttribute("reference", newValue) }

  /**
   * @returns {boolean}
   */
  hasReference() { return this._hasAttribute(this.reference()) }

  /**
   * @returns {Date | null}
   */
  createdAt() { return this.readAttribute("createdAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setCreatedAt(newValue) { return this._setColumnAttribute("createdAt", newValue) }

  /**
   * @returns {boolean}
   */
  hasCreatedAt() { return this._hasAttribute(this.createdAt()) }

  /**
   * @returns {Date | null}
   */
  updatedAt() { return this.readAttribute("updatedAt") }

  /**
   * @param {Date | string | null} newValue
   * @returns {void}
   */
  setUpdatedAt(newValue) { return this._setColumnAttribute("updatedAt", newValue) }

  /**
   * @returns {boolean}
   */
  hasUpdatedAt() { return this._hasAttribute(this.updatedAt()) }

  /**
   * @returns {import("../models/project.js").default}
   */
  createdProject() { return /** @type {import("../models/project.js").default} */ (this.getRelationshipByName("createdProject").loaded()) }

  /**
   * @abstract
   * @param {Record<string, ?>} [attributes]
   * @returns {import("../models/project.js").default}
   */
  buildCreatedProject(attributes) { void attributes; throw new Error("Not implemented") }

  /**
   * @abstract
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  loadCreatedProject() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<import("../models/project.js").default | undefined>}
   */
  createdProjectOrLoad() { return /** @type {Promise<import("../models/project.js").default | undefined>} */ (this.relationshipOrLoad("createdProject", {preloadTranslations: true})) }

  /**
   * @abstract
   * @param {import("../models/project.js").default} newModel
   * @returns {void}
   */
  setCreatedProject(newModel) { void newModel; throw new Error("Not implemented") }

  /**
   * @returns {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/user.js").default, typeof import("../models/authentication-token.js").default>}
   */
  authenticationTokens() { return /** @type {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/user.js").default, typeof import("../models/authentication-token.js").default>} */ (this.getRelationshipByName("authenticationTokens")) }

  /**
   * @returns {Array<import("../models/authentication-token.js").default>}
   */
  authenticationTokensLoaded() { return /** @type {Array<import("../models/authentication-token.js").default>} */ (this.getRelationshipByName("authenticationTokens").loaded()) }

  /**
   * @abstract
   * @returns {Promise<Array<import("../models/authentication-token.js").default>>}
   */
  loadAuthenticationTokens() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<Array<import("../models/authentication-token.js").default>>}
   */
  authenticationTokensOrLoad() { return /** @type {Promise<Array<import("../models/authentication-token.js").default>>} */ (this.relationshipOrLoad("authenticationTokens")) }

  /**
   * @abstract
   * @param {Array<import("../models/authentication-token.js").default>} newModels
   * @returns {void}
   */
  setAuthenticationTokens(newModels) { void newModels; throw new Error("Not implemented") }

  /**
   * @returns {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/user.js").default, typeof import("../models/project.js").default>}
   */
  createdProjects() { return /** @type {import("../../../../src/database/record/instance-relationships/has-many.js").default<typeof import("../models/user.js").default, typeof import("../models/project.js").default>} */ (this.getRelationshipByName("createdProjects")) }

  /**
   * @returns {Array<import("../models/project.js").default>}
   */
  createdProjectsLoaded() { return /** @type {Array<import("../models/project.js").default>} */ (this.getRelationshipByName("createdProjects").loaded()) }

  /**
   * @abstract
   * @returns {Promise<Array<import("../models/project.js").default>>}
   */
  loadCreatedProjects() { throw new Error("Not implemented") }

  /**
   * @returns {Promise<Array<import("../models/project.js").default>>}
   */
  createdProjectsOrLoad() { return /** @type {Promise<Array<import("../models/project.js").default>>} */ (this.relationshipOrLoad("createdProjects")) }

  /**
   * @abstract
   * @param {Array<import("../models/project.js").default>} newModels
   * @returns {void}
   */
  setCreatedProjects(newModels) { void newModels; throw new Error("Not implemented") }
}
